### ISSUE TITLE
zoneconditioning mode prep_cool not indicating cooling in HA

### ISSUE THREAD

**Issue by greggitter** [MizterB/homeassistant-infinitude-beyond#11]
I noticed recently that when my system is "dehumidifying" the HA interface SOMETIMES indicates idle.  In the evenings, the proxy server data element "zoneconditioning" will show "prep_cool" vs "active_cool".  The system however is doing the same thing, it's dehumidifying/cooling.  

When the system is "prep_cool", HA shows the system is idle, when it's "active_cool" it shows Cooling.  It just occurred to me why it is probably doing this.  I have a Sleep thermostat setting where we drop the temperature a couple degrees and "prep_cool" makes sense, it's "preparing" for that time period which is approaching.  Anyhow, hopefully this is an easy one.  Thank you for the time you've spent on this!

Here are a couple screen shots.

![active_cool](https://github.com/MizterB/homeassistant-infinitude-beyond/assets/68356047/f110d3a5-cb28-4943-832e-56085354450b)
![prep_cool](https://github.com/MizterB/homeassistant-infinitude-beyond/assets/68356047/c94529c7-67fc-4f52-96f1-786032f9e065)

**Comment by MizterB** [comment]
Thanks - did not know that state existed.  "prep_" zone conditioning states will be supported in the next release.
