### ISSUE TITLE
Activity unexpectedly changes to "Scheduled Activity" at midnight (rather than remain on "Sleep")

### ISSUE THREAD

**Issue by greggitter** [MizterB/homeassistant-infinitude-beyond#26]
This problem may be related to a recently closed problem where there were log messages indicating unknown activity.  Last night I happened to look just after the sleep schedule started (11:15).  HA indicated Sleep which is correct.  But at midnight, it changed from Sleep to Schedule Activity for no obvious reason.  This relates back to when the unknown activity log messages started in my case at midnight and ended at the start of the Wake schedule, 8:00 AM.  So there appears to still be some lingering issue here.  Here are a few screen shots that might help:

![image](https://github.com/user-attachments/assets/2da46afe-e38c-4236-ab24-c5997a22fd57)

![image](https://github.com/user-attachments/assets/f27c6c12-f6d6-476f-84b1-6c429bbf01ac)

![image](https://github.com/user-attachments/assets/ae053530-f344-4fd5-9147-1740bc0b07f5)

If there's any more information I can provide, let me know.  Also, @MizterB if there are some test/debugging code changes you want me to try, I have no problem manually editing files via editor in SSH to speed things up on your side.

**Comment by mrcushing** [comment]
Did you make sure your infinitude server is running the latest version?  That solves most of the problems.

**Comment by greggitter** [comment]
I believe I am current, I see no recent changes and should be notified.  Is there a way I can check…I don’t see a version number.  I am not using the docker version though…native install on a proxmox lxc.  Thx.

**Comment by mrcushing** [comment]
I don't know how to check, but infinitude had a major update about 9 months ago that fixed many issues people were experiencing

**Comment by greggitter** [comment]
OK, thanks.  It's not causing any issues at the moment just inconsistent with what's expected.  Based on the screenshots above, the data is being reported correctly from the proxy, right?  Anything more I can provide?

**Comment by MizterB** [comment]
I don't have a lot of time to look at this right now, but are your thermostat and HA server set to the same time zone?  Take a look at the "local time" (or similar) tag coming from Infinitude - I think it's in the status file?

**Comment by greggitter** [comment]
I checked the thermostat and the timestamp on the proxy page and HA and all are sync'd.  Not sure what you mean "status file"...glad to check just not sure where.  Thanks and like I said, everything is working so no urgency...I appreciate all you've done already.  Cheers!  :)

**Comment by greggitter** [comment]
I noticed infinitude code was updated a few days ago so went ahead yesterday to resync my git folder (not using docker).  Testing last night, this problem did not recur and did indicate "Sleep"...so either I didn't have the latest OR it was something in this latest update (?).  In any case, I'll close this issue since it is now resolved.  Thx!
