### ISSUE TITLE
Filter Level is not available?

### ISSUE THREAD

**Issue by greggitter** [MizterB/homeassistant-infinitude-beyond#3]
Hi, thanks for updating this module!  

This is just a question as I'm probably overlooking this.  I was converting my old infinitude to this new version and can't find the entity/attribute "filter level" (from fltrlvl in infinitude proxy server).  I see it referenced in api.py but I don't see it exposed in HA. 

Thanks!

**Comment by MizterB** [comment]
Looks like I just missed it - as you mention, I included it in the API!  Will get it added.
