### ISSUE TITLE
Remaining Preset Mode Icons

### ISSUE THREAD

**Issue by GitHubGoody** [MizterB/homeassistant-infinitude-beyond#8]
Any chance the remaining Preset Modes will also get icons?![image](https://github.com/MizterB/homeassistant-infinitude-beyond/assets/46235745/80f4f69d-da4c-4e3e-ad99-73d245b47af4)

**Comment by GitHubGoody** [comment]
More information [here](https://github.com/home-assistant/frontend/issues/19250#issuecomment-1886635795)

**Comment by MizterB** [comment]
I don't know how to do that.  The developer documentation does not describe how to add icons to custom presets as far as I can tell.  The ones that have icons in your image are out-of-the-box HA presets.

**Comment by MizterB** [comment]
Figured it out...fixed in 2024.6.0

**Comment by GitHubGoody** [comment]
Thanks!

**Comment by VoyteckPL** [comment]
How to add these custom icons?
